
package Wetterwerte;

import java.io.File;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;


public class WetterGUI extends javax.swing.JFrame {

    /**
     * Creates new form WetterGUI
     */
    public WetterGUI() {
        initComponents();
        
        lbtemp.setText("Temperatur: "+jstemp.getValue()+"°");
        lbluftf.setText("Luftfeuchtigkeit: "+jsluftfeuchtigkeit.getValue()+"%");
       
        
    }
        WetterModel wmodel= new WetterModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbtemp = new javax.swing.JLabel();
        jstemp = new javax.swing.JSlider();
        lbluftf = new javax.swing.JLabel();
        jsluftfeuchtigkeit = new javax.swing.JSlider();
        einfuegen = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        speichern = new javax.swing.JCheckBoxMenuItem();
        laden = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exit = new javax.swing.JCheckBoxMenuItem();
        serialisieren = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Eingabe"));
        jPanel2.setLayout(new java.awt.GridLayout(5, 0));
        jPanel2.add(lbtemp);

        jstemp.setMajorTickSpacing(10);
        jstemp.setMaximum(40);
        jstemp.setMinimum(-20);
        jstemp.setMinorTickSpacing(5);
        jstemp.setPaintLabels(true);
        jstemp.setPaintTicks(true);
        jstemp.setToolTipText("");
        jstemp.setValue(20);
        jstemp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onTempChange(evt);
            }
        });
        jPanel2.add(jstemp);
        jPanel2.add(lbluftf);

        jsluftfeuchtigkeit.setMajorTickSpacing(20);
        jsluftfeuchtigkeit.setMinorTickSpacing(10);
        jsluftfeuchtigkeit.setPaintLabels(true);
        jsluftfeuchtigkeit.setPaintTicks(true);
        jsluftfeuchtigkeit.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                onLuftfChange(evt);
            }
        });
        jPanel2.add(jsluftfeuchtigkeit);

        einfuegen.setText("Einfügen");
        einfuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onEinfuegen(evt);
            }
        });
        jPanel2.add(einfuegen);

        getContentPane().add(jPanel2);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Anzeige"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        list.setModel(wmodel);
        jScrollPane1.setViewportView(list);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        jMenu1.setText("File");

        speichern.setSelected(true);
        speichern.setText("Speichern");
        speichern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onSpeichern(evt);
            }
        });
        jMenu1.add(speichern);

        laden.setSelected(true);
        laden.setText("Laden ");
        laden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLaden(evt);
            }
        });
        jMenu1.add(laden);
        jMenu1.add(jSeparator1);

        exit.setSelected(true);
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onExit(evt);
            }
        });
        jMenu1.add(exit);

        serialisieren.setSelected(true);
        serialisieren.setText("jCheckBoxMenuItem1");
        serialisieren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialisierenActionPerformed(evt);
            }
        });
        jMenu1.add(serialisieren);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onEinfuegen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onEinfuegen
       //wmodel.add(new Wetterwert(jstemp.getValue(), jsluftfeuchtigkeit.getValue(), LocalDate.now(), LocalTime.now()));
       Wetterwert w = new Wetterwert(LocalDateTime.now(), jstemp.getValue(), jsluftfeuchtigkeit.getValue());
        wmodel.add(w);
        list.repaint();
    }//GEN-LAST:event_onEinfuegen

    private void onTempChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onTempChange
       lbtemp.setText("Temperatur: "+jstemp.getValue()+"°");
    }//GEN-LAST:event_onTempChange

    private void onLuftfChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_onLuftfChange
       lbluftf.setText("Luftfeuchtigkeit: "+jsluftfeuchtigkeit.getValue()+"%");
    }//GEN-LAST:event_onLuftfChange

    private void onExit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onExit
       System.exit(0);
    }//GEN-LAST:event_onExit

    private void onSpeichern(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSpeichern
       JFileChooser fc= new JFileChooser();
       fc.showSaveDialog(this);
       String pfad= fc.getSelectedFile().getPath();
       
       wmodel.save(String.format(pfad+".txt"));
       
    }//GEN-LAST:event_onSpeichern

    private void onLaden(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLaden
       JFileChooser fc= new JFileChooser();
       fc.showOpenDialog(this);
       String path= fc.getSelectedFile().getPath();
       
       wmodel.laden(path);
       
    }//GEN-LAST:event_onLaden

    private void serialisierenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialisierenActionPerformed
        JFileChooser fc= new JFileChooser();
       fc.showOpenDialog(this);
        try {
            wmodel.saveBin(fc.getSelectedFile());
        } catch (Exception ex) {
            Logger.getLogger(WetterGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_serialisierenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WetterGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton einfuegen;
    private javax.swing.JCheckBoxMenuItem exit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSlider jsluftfeuchtigkeit;
    private javax.swing.JSlider jstemp;
    private javax.swing.JCheckBoxMenuItem laden;
    private javax.swing.JLabel lbluftf;
    private javax.swing.JLabel lbtemp;
    private javax.swing.JList<Wetterwert> list;
    private javax.swing.JCheckBoxMenuItem serialisieren;
    private javax.swing.JCheckBoxMenuItem speichern;
    // End of variables declaration//GEN-END:variables
}
