/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laurapein
 */
public class AppointmentDlg extends javax.swing.JDialog {

    private int tag;
    private int monat;
    private int jahr;
    private int stunden;
    private int minuten;
    private String text;
    
    Appointment ap;
    
    boolean ok;
    /**
     * Creates new form AppointmentDlg
     */
    public AppointmentDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ok = true;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbTag = new javax.swing.JLabel();
        tfTag = new javax.swing.JTextField();
        lbMonat = new javax.swing.JLabel();
        tfMonat = new javax.swing.JTextField();
        lbJahr = new javax.swing.JLabel();
        tfJahr = new javax.swing.JTextField();
        lbStunde = new javax.swing.JLabel();
        tfStunde = new javax.swing.JTextField();
        lbMinute = new javax.swing.JLabel();
        tfMinute = new javax.swing.JTextField();
        lbText = new javax.swing.JLabel();
        tftext = new javax.swing.JTextField();
        btUebernehmen = new javax.swing.JButton();
        btAbbrechen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(7, 2));

        lbTag.setText("Tag");
        jPanel1.add(lbTag);
        jPanel1.add(tfTag);

        lbMonat.setText("Monat");
        jPanel1.add(lbMonat);
        jPanel1.add(tfMonat);

        lbJahr.setText("Jahr");
        jPanel1.add(lbJahr);
        jPanel1.add(tfJahr);

        lbStunde.setText("Stunde");
        jPanel1.add(lbStunde);
        jPanel1.add(tfStunde);

        lbMinute.setText("Minute");
        jPanel1.add(lbMinute);
        jPanel1.add(tfMinute);

        lbText.setText("Text");
        jPanel1.add(lbText);
        jPanel1.add(tftext);

        btUebernehmen.setText("Übernehmen");
        btUebernehmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onUebernehmen(evt);
            }
        });
        jPanel1.add(btUebernehmen);

        btAbbrechen.setText("Abbrechen");
        btAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAbbrechen(evt);
            }
        });
        jPanel1.add(btAbbrechen);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onUebernehmen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onUebernehmen
       tag = Integer.parseInt(tfTag.getText());
       monat = Integer.parseInt(tfMonat.getText());
       jahr = Integer.parseInt(tfJahr.getText());
       stunden = Integer.parseInt(tfStunde.getText());
       minuten = Integer.parseInt(tfMinute.getText());
       text = tftext.getText();
       
       
       ap= new Appointment(tag,monat,jahr,stunden,minuten,text);
       ok = true;
       dispose();
    }//GEN-LAST:event_onUebernehmen

    private void onAbbrechen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAbbrechen
        dispose();
        ok = false;
    }//GEN-LAST:event_onAbbrechen

     public void setTextFieldTag(int tag){
        tfTag.setText(""+tag);
    }
      public void setTextFieldMonat(int monat){
        tfTag.setText(""+monat);
    }
       public void setTextFieldJahr(int jahr){
        tfTag.setText(""+jahr);
    }
        public void setTextFieldStunden(int stunden){
        tfTag.setText(""+stunden);
    }
         public void setTextFieldMinuten(int minuten){
        tfTag.setText(""+minuten);
    }
          public void setTextFieldText(String text){
        tfTag.setText(text);
    }

    public int getTag() {
        return tag;
    }

    public int getMonat() {
        return monat;
    }

    public int getJahr() {
        return jahr;
    }

    public int getStunden() {
        return stunden;
    }

    public int getMinuten() {
        return minuten;
    }

    public String getText() {
        return text;
    }
          
    public Appointment getAppointment(){
        return ap;
    }
    
    public void clearAllTextFields() {
        tfTag.setText("");
        tfMonat.setText("");
        tfJahr.setText("");
        tfStunde.setText("");
        tfMinute.setText("");
        tftext.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppointmentDlg dialog = new AppointmentDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbbrechen;
    private javax.swing.JButton btUebernehmen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbJahr;
    private javax.swing.JLabel lbMinute;
    private javax.swing.JLabel lbMonat;
    private javax.swing.JLabel lbStunde;
    private javax.swing.JLabel lbTag;
    private javax.swing.JLabel lbText;
    private javax.swing.JTextField tfJahr;
    private javax.swing.JTextField tfMinute;
    private javax.swing.JTextField tfMonat;
    private javax.swing.JTextField tfStunde;
    private javax.swing.JTextField tfTag;
    private javax.swing.JTextField tftext;
    // End of variables declaration//GEN-END:variables
}
